baseURL = 'https://beka-birhanu.github.io/'
locale = 'en-us'
title = 'Beka Birhanu'

[markup]
  [markup.highlight]
    noClasses = false
    style = "catppuccin-mocha"
  [markup.goldmark.renderer]
    unsafe = true
